export const LOGIN_BEGIN = "LOGIN_BEGIN"
export const LOGIN_SUCCESFULL = "LOGIN_SUCCESFULL"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const LOGOUT = "LOGOUT"

export const POST_CATALOG_TYPE_NEW = "POST_CATALOG_TYPE_NEW"
export const POST_CATALOG_TYPE_HOT = "POST_CATALOG_TYPE_HOT"
export const POST_CATALOG_TYPE_SUBSCRIPTION = "POST_CATALOG_TYPE_SUBSCRIPTION"
export const POST_CATALOG_TYPE_USER_SUBSCRIPTION = "POST_CATALOG_TYPE_USER_SUBSCRIPTION"
export const POST_CATALOG_TYPE_BY_COMMUNITY = "POST_CATALOG_TYPE_BY_COMMUNITY"
export const POST_CATALOG_TYPE_BY_SEARCH = "POST_CATALOG_TYPE_BY_SEARCH";
export const POST_CATALOG_TYPE_BY_CREATOR = "POST_CATALOG_TYPE_BY_CREATOR";
export const POST_CATALOG_TYPE_BOOKMARKS = "POST_CATALOG_TYPE_BOOKMARKS";

export const POST_CATALOG_LOAD = "POST_CATALOG_LOAD";
export const POST_CATALOG_UNLOAD = "POST_CATALOG_UNLOAD";
export const POST_CATALOG_END = "POST_CATALOG_END";

export const POST_VIEW_LOAD = 13;
export const POST_VIEW_UNLOAD = 16;
export const POST_BOOKMARK_BEGIN = 35;
export const POST_BOOKMARK_SUCCESFULL = 36;
export const POST_BOOKMARK_FAILURE = 37;
export const POST_VOTE_BEGIN = 38;
export const POST_VOTE_SUCCESFULL = 39;
export const POST_VOTE_FAILURE = 40;
export const POST_RATING_UPDATE = 41;

export const CREATE_COMMENT_BEGIN = 17;
export const CREATE_COMMENT_SUCCESFULL = 18;
export const CREATE_COMMENT_FAILURE = 19;

export const GET_COMMENTS_LOAD = 20;
export const GET_COMMENTS_UNLOAD = 21;
export const GET_COMMENTS_END = 22;

export const USER_VIEW_LOAD = 26;
export const USER_VIEW_UNLOAD = 27;
export const USER_SUBSCRIPTION_LOAD = 100;

export const COMMUNITY_VIEW_LOAD = 30;
export const COMMUNITY_VIEW_UNLOAD = 31;
export const COMMUNITIES_CATALOG_UNLOAD = 35;
export const COMMUNITIES_CATALOG_LOAD = 36;

export const POST_CREATE_BEGIN = 32;
export const POST_CREATE_CHANGE = 33;
export const POST_CREATE_SUCCESFULL = 34;
