export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESFULL = "LOGIN_SUCCESFULL";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const POST_CATALOG_TYPE_NEW = "POST_CATALOG_TYPE_NEW";
export const POST_CATALOG_TYPE_HOT = "POST_CATALOG_TYPE_HOT";
export const POST_CATALOG_TYPE_SUBSCRIPTION = "POST_CATALOG_TYPE_SUBSCRIPTION";

export const POST_CATALOG_BEGIN = "POST_CATALOG_BEGIN";
export const POST_CATALOG_SUCCESFULL = "POST_CATALOG_SUCCESFULL";
export const POST_CATALOG_FAILURE = "POST_CATALOG_FAILURE";
