export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESFULL = "LOGIN_SUCCESFULL";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const POST_CATALOG_TYPE_NEW = "POST_CATALOG_TYPE_NEW";
export const POST_CATALOG_TYPE_HOT = "POST_CATALOG_TYPE_HOT";
export const POST_CATALOG_TYPE_SUBSCRIPTION = "POST_CATALOG_TYPE_SUBSCRIPTION";

export const POST_CATALOG_BEGIN = "POST_CATALOG_BEGIN";
export const POST_CATALOG_SUCCESFULL = "POST_CATALOG_SUCCESFULL";
export const POST_CATALOG_FAILURE = "POST_CATALOG_FAILURE";

export const GET_POST_BEGIN = "GET_POST_BEGIN";
export const GET_POST_SUCCESFULL = "GET_POST_SUCCESFULL";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const CREATE_COMMENT_BEGIN = "CREATE_COMMENT_BEGIN";
export const CREATE_COMMENT_SUCCESFULL = "CREATE_COMMENT_SUCCESFULL";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

export const GET_COMMENTS_BEGIN = "GET_COMMENTS_BEGIN";
export const GET_COMMENTS_SUCCESFULL = "GET_COMMENTS_SUCCESFULL";
export const GET_COMMENTS_EMPTY = "GET_COMMENTS_EMPTY";

