export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_WRONG_CREDENTIALS = "LOGIN_WRONG_CREDENTIALS";
export const LOGIN_USER_NOT_FOUND = "LOGIN_USER_NOT_FOUND";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const NEW_POSTS_BEGIN = "NEW_POSTS_BEGIN";
export const NEW_POSTS_SUCCESS = "NEW_POSTS_SUCCESS";
export const NEW_POSTS_FAILURE = "NEW_POSTS_FAILURE";

export const HOT_POSTS_BEGIN = "HOT_POSTS_BEGIN";
export const HOT_POSTS_SUCCESS = "HOT_POSTS_SUCCESS";
export const HOT_POSTS_FAILURE = "HOT_POSTS_FAILURE";

export const SUBSCRIPTION_POSTS_BEGIN = "SUBSCRIPTION_POSTS_BEGIN";
export const SUBSCRIPTION_POSTS_SUCCESS = "SUBSCRIPTION_POSTS_SUCCESS";
export const SUBSCRIPTION_POSTS_FAILURE = "SUBSCRIPTION_POSTS_FAILURE";

export const POST_BEGIN = "POST_BEGIN";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAILURE = "POST_FAILURE";

export const USER_BEGIN = "USER_BEGIN";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";

export const COMMENTS_BEGIN = "COMMENTS_BEGIN";
export const COMMENTS_SUCCESS = "COMMENTS_SUCCESS";
export const COMMENTS_FAILURE = "COMMENTS_FAILURE";
